name: Publish package to GitHub Packages
on: push
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: '[{"id": "github", "username": "JAVA_TOKEN", "password": "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"}]'
          
      - name: Publish package
        run: mvn -X -Dmaven.resolver.transport=wagon --batch-mode deploy
        env:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
